Language: MS SQL

/*
Enter your query here.
Please append a semicolon ";" at the end of the query and enter your query in a single line to avoid error.
*/
SELECT MIN(DOC), MIN(PROF),MIN(SINGER),MIN(ACTOR)
FROM
    (SELECT
        COUNT(*) OVER(PARTITION BY OCCUPATION ORDER  BY NAME) AS R_NUMBER,
        CASE WHEN OCCUPATION = 'DOCTOR' THEN NAME ELSE NULL END AS DOC,
        CASE WHEN OCCUPATION = 'PROFESSOR' THEN NAME ELSE NULL END AS PROF,
        CASE WHEN OCCUPATION = 'ACTOR' THEN NAME ELSE NULL END ACTOR,
        CASE WHEN OCCUPATION = 'SINGER' THEN NAME ELSE NULL END SINGER
     FROM OCCUPATIONS) AS TMP GROUP BY R_NUMBER
